help: ## Show this help.
	@fgrep -h "##" $(MAKEFILE_LIST) | fgrep -v fgrep | sed -e 's/##//'


build: ## validate terraform stack
	echo "check back"


test: ## launch a docker container 
	echo "launch test"



